apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-info-service-config
  namespace: customer-info
data:
  CUSTOMER_INFO_APPLICATION_PROFILE: prod
  apigate.db.url: jdbc:postgresql://10.69.129.17:5432/customer_info_service_prod
  apigate.db.schema: customer_info_service
  apigate.instance.port: "8090"
  apigate.db.pool.size: "30"
  apigate.server.threads.max: "30"
  apigate.server.monitoring.port: "8091"
  apigate.server.monitoring.threads.max: "10"
  apigate.redis.host: 10.69.131.4
  apigate.redis.port: "6379"
  apigate.cust-info.mask: XXXXXXXXX
  apigate.cust-info.operator.endpoint.path-variable.msisdn: msisdn
  apigate.cust-info.operator.token.refresh.ttl: 120
  apigate.cust-info.operator.token.refresh.scheduler: 60
  apigate.http.client.timeout: 5
  apigate.db.deploy: true