apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-info-service-config
  namespace: customer-info
data:
  CUSTOMER_INFO_APPLICATION_PROFILE: prod
  apigate.db.url: jdbc:postgresql://10.69.129.7:5432/prod_customer_info_service
  apigate.db.schema: customer_info_service
  apigate.instance.port: "8090"
  apigate.db.pool.size: "30"
  apigate.server.threads.max: "30"
  apigate.server.monitoring.port: "8091"
  apigate.server.monitoring.threads.max: "10"