apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blacklist-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blacklist-service
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
