apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customer-info-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-info-service
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
