apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-info-service-canary
  namespace: customer-info
  labels:
    app: customer-info-service
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-info-service
      version : canary
  template:
    metadata:
      labels:
        app: customer-info-service
        version: canary
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: stg-application2
      containers:
      - name: customer-info-service
        image: 'gcr.io/project-apigate-stg-hub/customer-info-service:${trigger[''tag'']}'
        ports:
        - containerPort: 8090
        - containerPort: 8091
        readinessProbe:
          httpGet:
            path: /monitor/health
            port: 8091
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 0.5
            memory: "1Gi"
        env:
        - name: CUSTOMER_INFO_APPLICATION_PROFILE
          valueFrom:
            configMapKeyRef:
              key: CUSTOMER_INFO_APPLICATION_PROFILE
              name: customer-info-service-config
        - name: apigate.db.url
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.db.url     
        - name: apigate.db.schema
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.db.schema
        - name: apigate.instance.port
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.instance.port
        - name: apigate.db.pool.size
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.db.pool.size
        - name: apigate.server.threads.max
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.server.threads.max
        - name: apigate.db.username
          valueFrom:
            secretKeyRef:
              name: customer-info-service-secret
              key: apigate.db.username
        - name: apigate.db.password
          valueFrom:
            secretKeyRef:
              name: customer-info-service-secret
              key: apigate.db.password
        - name: apigate.server.monitoring.port
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.server.monitoring.port
        - name: apigate.server.monitoring.threads.max
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.server.monitoring.threads.max
        - name: apigate.redis.host
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.redis.host
        - name: apigate.redis.port
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.redis.port
        - name: apigate.redis.password
          valueFrom:
            secretKeyRef:
              name: customer-info-service-secret
              key: apigate.redis.password
        - name: apigate.cust-info.mask
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.cust-info.mask
        - name: apigate.cust-info.operator.endpoint.path-variable.msisdn
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.cust-info.operator.endpoint.path-variable.msisdn
        - name: apigate.cust-info.operator.token.refresh.ttl
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.cust-info.operator.token.refresh.ttl
        - name: apigate.cust-info.operator.token.refresh.scheduler
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.cust-info.operator.token.refresh.scheduler
        - name: apigate.http.client.timeout
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.http.client.timeout
        - name: apigate.db.deploy
          valueFrom:
            configMapKeyRef:
              name: customer-info-service-config
              key: apigate.db.deploy